module.exports = {
    plugins: ['stylelint-order'],
    rules: {
        'block-closing-brace-newline-after': 'always',
        'block-closing-brace-newline-before': 'always',
        'block-no-empty': true,
        'block-opening-brace-newline-after': 'always',
        'block-opening-brace-newline-before': 'never-single-line',
        'color-no-invalid-hex': true,
        'declaration-block-no-duplicate-properties': true,
        'declaration-block-no-shorthand-property-overrides': true,
        'declaration-block-semicolon-newline-after': 'always',
        'declaration-block-semicolon-space-before': 'never',
        'declaration-block-trailing-semicolon': 'always',
        'declaration-colon-space-before': 'never',
        'declaration-no-important': true,
        'declaration-property-value-no-unknown': true,
        'function-calc-no-unspaced-operator': true,
        'function-linear-gradient-no-nonstandard-direction': true,
        'indentation': 4,
        'length-zero-no-unit': true,
        'linebreaks': 'unix',
        'max-empty-lines': 1,
        'no-duplicate-selectors': true,
        'no-eol-whitespace': true,
        'order/order': ['custom-properties', 'declarations'],
        'order/properties-alphabetical-order': true,
        'selector-descendant-combinator-no-non-space': true,
        'selector-list-comma-newline-after': 'always',
        'selector-list-comma-space-before': 'never'
    }
};
